/**
 * This script was generated by Loon to simulate http requests.
 */
try{
    let url = "https://cv.intgold.cn/api/quan/v1/boards/tjb/entries";
    let chars = "0123456789abcdef";
    let uuid = "";
    for(let i=0;i<36;i++){
        if(i===8||i===13||i===18||i===23) uuid+="-";
        else if(i===14) uuid+="4";
        else if(i===19) uuid+=chars[Math.floor(Math.random()*4)+8];
        else uuid+=chars[Math.floor(Math.random()*16)];
    }

    const uaList = [
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1"
    ];
    const randomUA = uaList[Math.floor(Math.random()*uaList.length)];

    const langList = ["zh-CN,zh;q=0.9","zh-CN,zh;q=0.85","zh-CN,zh;q=0.8"];
    const randomLang = langList[Math.floor(Math.random()*langList.length)];
    let headers = {
        'priority':'u=3, i',
        'origin':'https://cv.intgold.cn',
        'content-type':'application/json',
        'accept-language':randomLang,
        'x-copygo-display-name':"v_" + uuid.split("-")[0],
        'content-length':'137',
        'x-copygo-client-key':uuid,
        'user-agent':randomUA,
        'accept-encoding':'gzip, deflate, br, zstd',
        'accept':'application/json',
    };
    let body = {
        raw_text: $argument.postBody,
        agreed: true,
        extra_email: "",
        max_use_times: 1
    };
    var params = {
        url:url,
        timeout:5000,
        headers:headers,
        alpn:'h2',
        body:body,
    };

    $httpClient.post(params, function(e,resp,resBody) {
        try {
            // 网络异常
            if (e) throw new Error(`网络错误:${e.message}`);

            // 解析返回
            const res = JSON.parse(resBody);
            // 非成功码一律判定失败
            if (res.code !== 200) throw new Error(`服务端错误 ${res.code}: ${res.message}`);
            console.log("Response Status: " + resp.status);
            //console.log("Response Headers: " + JSON.stringify(response.headers));
            console.log("Response Body: " + resBody);
            // 成功，静默结束
            $done();
        } catch (innerErr) {
            // 任何回调内错误
            console.log("脚本异常", "", innerErr.message)
            $notification.post("脚本异常", "", innerErr.message);
            $done({ disable: true });
        }
  
        // if (errormsg) {
        //     console.log(errormsg);
        //     $notify("执行失败", "", errormsg);
        //     $done({disable:true});
    
        // } else {
        //     console.log("Response Status: " + response.status);
        //     //console.log("Response Headers: " + JSON.stringify(response.headers));
        //     console.log("Response Body: " + data);
        // }
        // $done();
    });
} catch (outerErr) {
  // 代码本身语法/变量/任何全局报错
  console.log("脚本崩溃", "", outerErr.message)
  $notification.post("脚本崩溃", "", outerErr.message);
  $done({ disable: true });
}




// let chars = "0123456789abcdef";
// let uuid = "";
// for(let i=0;i<36;i++){
//   if(i===8||i===13||i===18||i===23) uuid+="-";
//   else if(i===14) uuid+="4";
//   else if(i===19) uuid+=chars[Math.floor(Math.random()*4)+8];
//   else uuid+=chars[Math.floor(Math.random()*16)];
// }

// const uaList = [
//   "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1",
//   "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1"
// ];
// const randomUA = uaList[Math.floor(Math.random()*uaList.length)];

// const langList = ["zh-CN,zh;q=0.9","zh-CN,zh;q=0.85","zh-CN,zh;q=0.8"];
// const randomLang = langList[Math.floor(Math.random()*langList.length)];

// // 彻底清指纹，必做
// delete $request.headers.cookie;
// delete $request.headers["sec-ch-ua"];
// delete $request.headers["sec-ch-ua-mobile"];
// delete $request.headers["sec-ch-ua-platform"];
// delete $request.headers["sec-fetch-site"];
// delete $request.headers["sec-fetch-mode"];
// delete $request.headers["sec-fetch-dest"];
// delete $request.headers.referer;

// $request.headers["user-agent"] = randomUA;
// $request.headers["x-copygo-client-key"] = uuid;
// $request.headers["x-copygo-display-name"] = "v_" + uuid.split("-")[0];
// $request.headers["accept-language"] = randomLang;

// $done({headers:$request.headers});